layout_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.2859416
  lightness: 1
  rhythmicContrast: 0.5985663
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.437276
name: Mile High Drones
